spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

oauth2:
  kakao:
    api-key: ${KAKAO_APP_KEY}
    token-api-url: https://kauth.kakao.com/oauth/token
    public-key-info: https://kauth.kakao.com/.well-known/jwks.json
  apple:
    api-key: ${APPLE_APP_KEY}
    token-api-url: https://appleid.apple.com/auth/token
    public-key-info: https://appleid.apple.com/auth/keys
  google:
    api-key: ${GOOGLE_APP_KEY}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-api-url: https://oauth2.googleapis.com/token
    public-key-info: https://www.googleapis.com/oauth2/v3/certs

redis:
  host: localhost
  port: 6379

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.yaml
    path: /docs/swagger